on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: osu! multiplayer rooms
        env:
          ACCESS_TOKEN: ${{ secrets.OSU_ACCESS_TOKEN }}
        run: |-
          curl --request GET --get "https://osu.ppy.sh/api/v2/rooms" --header "Content-Type: application/json" --header "Accept: application/json" --header "Authorization: Bearer $ACCESS_TOKEN"
