on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: "secrets"
      - name: Refresh osu!
        env:
          PASS: ${{ secrets.SECRETS_PASSPHRASE }}
        run: |-
          CLIENT_ID=$(gpg --quiet --batch --yes --decrypt --passphrase="$PASS" osu/client_id.gpg)
          CLIENT_SECRET=$(gpg --quiet --batch --yes --decrypt --passphrase="$PASS" osu/client_secret.gpg)
          REFRESH_TOKEN=$(gpg --quiet --batch --yes --decrypt --passphrase="$PASS" osu/refresh_token.gpg)
          curl --fail-with-body --request POST "https://osu.ppy.sh/oauth/token" --header "Accept: application.json" --header "Content-Type: application/x-www-form-urlencoded" --data "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=refresh_token&refresh_token=$REFRESH_TOKEN" -o response.json
          rm osu/refresh_token.gpg
          rm osu/access_token.gpg
          jq -r .access_token response.json | gpg --quiet --batch --yes --symmetric --cipher-algo AES256 --passphrase="$PASS" --output osu/access_token.gpg
          jq -r .refresh_token response.json | gpg --quiet --batch --yes --symmetric --cipher-algo AES256 --passphrase="$PASS" --output osu/refresh_token.gpg
          rm response.json
          git config --global user.name '424ever'
          git config --global user.email '424ever@users.noreply.github.com'
          git add osu/refresh_token.gpg
          git add osu/access_token.gpg
          git commit --allow-empty -m 'refresh osu! tokens'
          git push
